set $bg       #0d160f
set $fg       #f6fff0
set $inactive #203322
set $accent   #a7c957
set $urgent   #c75c5c
client.focused          $accent $accent #071007 $accent $accent
client.focused_inactive $inactive $inactive $fg $inactive $inactive
client.unfocused        $bg $bg $fg $bg $bg
client.urgent           $urgent $urgent $fg $urgent $urgent
client.placeholder      $bg $bg $fg $bg $bg
